## For Snakemake to recognize this file it must be named config.yaml.
## Specific information to our HPC configuration has been replaced in this example with <CAPITAL LETTERS>
## Please edit to include the configuration of the cluster you are using

### How Snakemake will run on SBATCH ###
cores: 60
jobs: 10 
latency-wait: 60 
rerun-incomplete: true
retries: 2              
max-jobs-per-second: 2 
executor: slurm

# Reevaluate completed jobs when inputs, parameters, environments or code change
## flags available [input, mtime, params, software-env, code, resources, none]
rerun-triggers: [input, params, software-env, code]

### Env Vars ###
envvars:
  - TMPDIR  # Export a writable job scratch path before invoking Snakemake.

default-resources:
  - slurm_account=<ACCOUNT_NAME>
  - slurm_partition=<PARTITION_NAME>
  - clusters=<CLUSTER_NAME>
  - qos=<QOS_LEVEL>      # e.g., 'low' if jobs are held in queue for long
  - runtime=<RUNTIME_MINUTES>  # e.g., 60
  - mem_mb=<MEMORY_MB>         # e.g., 4000

### Env modules ###
# use-envmodules: false 

### Conda ###
use-conda: true
conda-frontend: mamba   

### Resource scopes ###
set-resource-scopes:
  cores: local 

## Per rule resources
set-resources:
  fastp_pe:
    mem_mb: 4000
    runtime: 40

  bowtie2_align:
    mem_mb: 48000
    runtime: 120

  extract_unmapped_fastq:
    mem_mb: 64000
    runtime: 120

  sortmerna_pe:
    mem_mb: 32000
    runtime: 360

  kraken2:
    slurm_partition: <LARGE_PARTITION_NAME>
    slurm_account: <LARGE_ACCOUNT_NAME>
    mem_mb: 600000
    runtime: 30

  bracken:
    mem_mb: 4000
    runtime: 10

  combine_bracken_outputs:
    mem_mb: 2000
    runtime: 20

  bracken_extract:
    mem_mb: 2000
    runtime: 10

  rgi_validate_database:
    mem_mb: 2000
    runtime: 30

  rgi_bwt:
    mem_mb: 64000
    runtime: 60

  rna_spades:
    mem_mb: 64000
    runtime: 240

  rnaquast_busco:
    mem_mb: 16000
    runtime: 120

  megahit_coassembly:
    mem_mb: 256000
    runtime: 720

  index_coassembly:
    mem_mb: 16000
    runtime: 120

  bowtie2_map_transcripts:
    mem_mb: 32000
    runtime: 720

  assembly_stats_depth:
    mem_mb: 2000
    runtime: 30

  prodigal_genes:
    mem_mb: 2000
    runtime: 60

  featurecounts:
    mem_mb: 8000
    runtime: 10

  prepare_cazyme_proteins:
    mem_mb: 2000
    runtime: 30

  cazyme_annotation:
    mem_mb: 16000
    runtime: 240

  cazyme_rna_counts:
    mem_mb: 8000
    runtime: 30
